version: '3'

services:
  airflow:
    build: ./docker-build
    image: ${AIRFLOW_IMAGE_NAME:-airflow:2.4.2-spark-3.3.1}
    container_name: AIRFLOW
    command: standalone
    user: "${AIRFLOW_UID:-50000}:0"
    environment:
      _AIRFLOW_DB_UPGRADE: "true"
      _AIRFLOW_WWW_USER_CREATE: "true"
      _AIRFLOW_WWW_USER_PASSWORD_CMD: ${_AIRFLOW_WWW_USER_PASSWORD_CMD:-echo admin}
      AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "false"
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: "sqlite:////home/airflow/airflow.db"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./work-dir:/opt/airflow/work-dir
    ports:
      - 8080:8080

networks:
  default:
    name: LAB